styles = {
    "Canon50": "Canon-50 style: make the picture into a camera photograph, realistic picture.",
    "Octane": "Octane style: movie-like with cinematic effects, looking like Disney characters.",
    "8k":" 8k style: slightly increase the image definition, make the image more camera like and realistic",
    "Close-up": "Close-up style: make the image more close-up, and the image is more realistic, with bigger breasts and defined faces",
    "Cezanne": "Cezanne style: make the image more like a painting, with a less realistic face and a less realistic body",
    "Cubist": "Cubist style: make the image more like a Pablo Picasso painting", 
    "Seductive": "Seductive style: makes females more adult, adds quality breasts to their photos. Make men have defined jaws and muscled bodies",
    "Candy": "Candy style: make the image more pastelated, with vivid colors and a predoimance of pink and blue",
    "Art germ": "By art germ",
    "Comic book": "Comic book style: make the image more like a comic book, with vivid colors assimilating Marvel and DC comics",
    "Dramatic cinematic": "Dramatic cinematic lighting style: make the image more like a movie, with dramatic lighting and a cinematic effect",
    "Portrait": "Portrait style: make the image more like a portrait, with an increased emphasis on the face and a blurring of the background",
    "Pencil": "Pencil style: make the image more like a pencil drawing, with sharp, pencil-like countours",
    "wlop" : "wlop",
    "Hyper realistic": "Hyper realistic style: make the image more like a hyper realistic image, with a lot of details and a lot of colors",
    "Anime": "Anime style: make the image more like an anime, with bigger eyes, longer hair, and well-defined bodies",
    "Vivacious": "Vivacious style: improved posing in more dramatic positions",
    "Cathedral": "Cathedral style: make the image acquire a medieval Catholic aesthetic",
}